// Modul: KESEHATAN — Barrel Export
export { default as TenagaKesehatanDashboard } from './TenagaKesehatanDashboard';
export { default as BookingManagement } from './BookingManagement';
export { default as ScheduleManagement } from './ScheduleManagement';
export { default as PatientList } from './PatientList';
export { default as PatientMedicalRecord } from './PatientMedicalRecord';
export { default as InsuranceReview } from './InsuranceReview';
export { default as BAPManagement } from './BAPManagement';
export { default as ReferralManagement } from './ReferralManagement';
export { default as ReportsPage } from './ReportsPage';
export { default as Settings } from './Settings';
export { default as NotificationsCenter } from './NotificationsCenter';
export { default as AdminTenagaKesehatanList } from './AdminTenagaKesehatanList';
export { default as AdminTenagaKesehatanDashboard } from './AdminTenagaKesehatanDashboard';
export { default as AdminTenagaKesehatanBookings } from './AdminTenagaKesehatanBookings';
export { default as AdminTenagaKesehatanMedicalRecords } from './AdminTenagaKesehatanMedicalRecords';
export { default as AdminTenagaKesehatanReferrals } from './AdminTenagaKesehatanReferrals';
export { default as AdminKlaimAsuransi } from './AdminKlaimAsuransi';
export { default as FacultyKesehatan } from './FacultyKesehatan';
