package routes

import (
	"siakad-backend/controllers"
	"siakad-backend/controllers/kencana"
	"siakad-backend/middleware"

	"github.com/gofiber/fiber/v2"
)

func SetupKencanaRoutes(app *fiber.App) {
	api := app.Group("/api", middleware.AuthProtected)

	student := api.Group("/kencana-student", middleware.MahasiswaCheck)
	student.Get("/dashboard", kencana.GetDashboard)
	student.Get("/mentor-invitations", kencana.GetMentorInvitations)
	student.Post("/mentor-invitations/:id/respond", kencana.RespondMentorInvitation)
	student.Post("/group-invitations/:id/respond", kencana.RespondGroupInvitation)
	student.Get("/timeline", kencana.GetTimeline)
	student.Get("/stages/:stageId", kencana.GetStage)
	student.Get("/sessions/:sessionId", kencana.GetSession)
	student.Post("/materials/:materialId/complete", kencana.CompleteMaterial)
	student.Get("/quizzes/:quizId", kencana.GetQuiz)
	student.Post("/quizzes/:quizId/start", kencana.StartQuiz)
	student.Post("/quiz-attempts/:attemptId/answers", kencana.SaveQuizAnswer)
	student.Post("/quiz-attempts/:attemptId/submit", kencana.SubmitQuizAttempt)
	student.Get("/assignments/:assignmentId", kencana.GetAssignment)
	student.Post("/assignments/:assignmentId/submit", kencana.SubmitAssignment)
	student.Get("/handbook", kencana.GetHandbook)
	student.Post("/handbook/draft", kencana.SaveHandbookDraft)
	student.Post("/handbook/submit", kencana.SubmitHandbook)
	student.Post("/attendance", kencana.StudentSubmitAttendance)
	student.Get("/attendance", kencana.GetAttendance)
	student.Get("/score", kencana.GetScore)
	student.Get("/banding", kencana.GetBanding)
	student.Post("/banding", kencana.SubmitBanding)
	student.Get("/remedial", kencana.GetRemedial)
	student.Get("/certificate", kencana.GetCertificate)

	admin := api.Group("/kencana-admin", middleware.KencanaAdminCheck)
	admin.Get("/faculties", controllers.GetAllFakultas)
	admin.Get("/majors", controllers.GetAllProgramStudi)
	// Dashboard Stats
	admin.Get("/dashboard/stats", middleware.RequirePermission("kencana.timeline.view"), kencana.GetDashboardStats)
	// Periods
	admin.Get("/periods", middleware.RequirePermission("kencana.timeline.view"), kencana.ListPeriods)
	admin.Post("/periods", middleware.RequirePermission("kencana.timeline.create"), kencana.CreatePeriod)

	admin.Get("/periods/:id/phases", middleware.RequirePermission("kencana.timeline.view"), kencana.GetPeriodPhases)
	admin.Put("/periods/:id/timeline/:phaseType", middleware.RequirePermission("kencana.timeline.update"), kencana.UpdateTimelinePhase)
	admin.Post("/periods/:id/university/:action", middleware.RequirePermission("kencana.timeline.update"), kencana.UpdateUniversityPhase)
	admin.Post("/periods/:id/faculty/open", middleware.RequirePermission("kencana.timeline.update"), kencana.OpenFacultyPhases)
	// Media Upload
	admin.Post("/upload", middleware.RequirePermission("kencana.university.create"), kencana.UploadMedia)
	// Stages
	admin.Get("/stages", middleware.RequirePermission("kencana.university.view"), kencana.ListStages)
	admin.Post("/stages", middleware.RequirePermission("kencana.university.create"), kencana.CreateStage)
	admin.Put("/stages/:id", middleware.RequirePermission("kencana.university.update"), kencana.UpdateStage)
	// Sessions
	admin.Get("/sessions", middleware.RequirePermission("kencana.university.view"), kencana.ListSessions)
	admin.Get("/sessions/:id", middleware.RequirePermission("kencana.university.view"), kencana.GetAdminSessionDetail)
	admin.Post("/sessions", middleware.RequirePermission("kencana.university.create"), kencana.CreateSession)
	admin.Put("/sessions/:id", middleware.RequirePermission("kencana.university.update"), kencana.UpdateSession)
	admin.Delete("/sessions/:id", middleware.RequirePermission("kencana.university.delete"), kencana.DeleteSession)
	admin.Get("/sessions/:id/qr-token", middleware.RequirePermission("kencana.university.view"), kencana.GetSessionQRToken)
	admin.Post("/sessions/:id/qr-token/regenerate", middleware.RequirePermission("kencana.university.update"), kencana.RegenerateQRToken)
	// Materials (CRUD + file upload)
	admin.Post("/materials", middleware.RequirePermission("kencana.university.create"), kencana.CreateMaterial)
	admin.Put("/materials/:id", middleware.RequirePermission("kencana.university.update"), kencana.UpdateMaterial)
	admin.Delete("/materials/:id", middleware.RequirePermission("kencana.university.delete"), kencana.DeleteMaterial)
	admin.Post("/materials/upload", middleware.RequirePermission("kencana.university.create"), kencana.UploadMaterial)
	// Quizzes & Questions
	admin.Post("/quizzes", middleware.RequirePermission("kencana.university.create"), kencana.CreateQuiz)
	admin.Put("/quizzes/:id", middleware.RequirePermission("kencana.university.update"), kencana.UpdateQuiz)
	admin.Delete("/quizzes/:id", middleware.RequirePermission("kencana.university.delete"), kencana.DeleteQuiz)
	admin.Get("/quizzes/:id", middleware.RequirePermission("kencana.university.view"), kencana.GetQuizDetail)
	admin.Post("/questions", middleware.RequirePermission("kencana.university.create"), kencana.CreateQuestion)
	admin.Put("/questions/:id", middleware.RequirePermission("kencana.university.update"), kencana.UpdateQuestion)
	// Assignments (CRUD)
	admin.Post("/assignments", middleware.RequirePermission("kencana.university.create"), kencana.CreateAssignment)
	admin.Put("/assignments/:id", middleware.RequirePermission("kencana.university.update"), kencana.UpdateAssignment)
	admin.Delete("/assignments/:id", middleware.RequirePermission("kencana.university.delete"), kencana.DeleteAssignment)
	// Participants & Scores
	admin.Get("/participants", middleware.RequirePermission("kencana.participants.view"), kencana.ListParticipants)
	admin.Get("/scores/export-pdf", middleware.RequirePermission("kencana.scores.view"), kencana.AdminDownloadScoresPDF)
	admin.Get("/scores/export-excel", middleware.RequirePermission("kencana.scores.view"), kencana.AdminDownloadScoresExcel)
	admin.Get("/scores", middleware.RequirePermission("kencana.scores.view"), kencana.ListScores)
	admin.Get("/score-items", middleware.RequirePermission("kencana.scores.view"), kencana.AdminListScoreItems)
	admin.Post("/score-items", middleware.RequirePermission("kencana.scores.create"), kencana.UpsertScoreItem)
	admin.Post("/score-items/bulk", middleware.RequirePermission("kencana.scores.create"), kencana.BulkUpsertScoreItems)
	admin.Get("/scores/summary", middleware.RequirePermission("kencana.score_summary.view"), kencana.ScoreSummary)
	admin.Post("/scores/calculate", middleware.RequirePermission("kencana.scores.update"), kencana.CalculateAllScores)
	// Remedials & Certificates
	admin.Get("/remedials", middleware.RequirePermission("kencana.remedials.view"), kencana.ListRemedials)
	admin.Post("/remedials", middleware.RequirePermission("kencana.remedials.create"), kencana.CreateRemedial)
	admin.Get("/certificates", middleware.RequirePermission("kencana.certificates.view"), kencana.ListCertificates)
	admin.Get("/certificates/:id", middleware.RequirePermission("kencana.certificates.view"), kencana.GetCertificateDetail)
	admin.Post("/certificates/generate", middleware.RequirePermission("kencana.certificates.create"), kencana.GenerateCertificate)
	admin.Post("/certificates/generate-bulk", middleware.RequirePermission("kencana.certificates.create"), kencana.GenerateBulkCertificates)
	
	// Certificate Settings
	admin.Get("/certificate-settings", middleware.RequirePermission("kencana.settings.view"), kencana.GetCertificateSettings)
	admin.Put("/certificate-settings", middleware.RequirePermission("kencana.settings.view"), kencana.UpdateCertificateSettings)
	admin.Post("/certificate-settings/logo", middleware.RequirePermission("kencana.settings.view"), kencana.UploadCertificateLogo)
	admin.Post("/certificate-settings/left-logo", middleware.RequirePermission("kencana.settings.view"), kencana.UploadCertificateLeftLogo)
	admin.Post("/certificate-settings/right-logo", middleware.RequirePermission("kencana.settings.view"), kencana.UploadCertificateRightLogo)
	// Banding
	admin.Get("/banding", middleware.RequirePermission("kencana.scores.view"), kencana.AdminListBanding)
	admin.Put("/banding/:id", middleware.RequirePermission("kencana.scores.update"), kencana.AdminRespondBanding)
	// Mentors
	admin.Get("/mentors", middleware.RequirePermission("kencana.mentors.view"), kencana.ListMentors)
	admin.Get("/students", middleware.RequirePermission("kencana.mentors.view"), kencana.SearchStudents)
	admin.Post("/mentors", middleware.RequirePermission("kencana.mentors.create"), kencana.CreateMentor)
	admin.Put("/mentors/:id", middleware.RequirePermission("kencana.mentors.update"), kencana.UpdateMentor)
	admin.Delete("/mentors/:id", middleware.RequirePermission("kencana.mentors.delete"), kencana.DeleteMentor)
	admin.Get("/mentor-assignments", middleware.RequirePermission("kencana.mentors.view"), kencana.ListMentorAssignments)
	admin.Post("/mentor-assignments", middleware.RequirePermission("kencana.mentors.create"), kencana.CreateMentorAssignment)
	admin.Put("/mentor-assignments/:id/move", middleware.RequirePermission("kencana.mentors.update"), kencana.MoveMentorAssignment)
	admin.Delete("/mentor-assignments/:id", middleware.RequirePermission("kencana.mentors.delete"), kencana.DeleteMentorAssignment)
	// Groups
	admin.Get("/groups", middleware.RequirePermission("kencana.groups.view"), kencana.ListGroups)
	admin.Post("/groups", middleware.RequirePermission("kencana.groups.create"), kencana.CreateGroup)
	admin.Post("/groups/auto-assign", middleware.RequirePermission("kencana.groups.create"), kencana.AutoAssignGroups)
	admin.Get("/groups/:id", middleware.RequirePermission("kencana.groups.view"), kencana.GetGroup)
	admin.Put("/groups/:id", middleware.RequirePermission("kencana.groups.update"), kencana.UpdateGroup)
	admin.Delete("/groups/:id", middleware.RequirePermission("kencana.groups.delete"), kencana.DeleteGroup)
	admin.Post("/groups/:id/members", middleware.RequirePermission("kencana.groups.update"), kencana.AddGroupMembers)
	admin.Delete("/groups/:id/members/:studentId", middleware.RequirePermission("kencana.groups.delete"), kencana.RemoveGroupMember)
	// Announcements
	admin.Get("/announcements", middleware.RequirePermission("kencana.announcement.view"), kencana.ListAnnouncements)
	admin.Post("/announcements", middleware.RequirePermission("kencana.announcement.create"), kencana.CreateAnnouncement)
	admin.Delete("/announcements/:id", middleware.RequirePermission("kencana.announcement.delete"), kencana.DeleteAnnouncement)
	// Dev: Reset all Kencana data
	admin.Post("/reset-data", kencana.ResetKencanaData)

	fakultas := api.Group("/kencana-fakultas", middleware.KencanaFakultasCheck)
	fakultas.Get("/dashboard/stats", kencana.GetDashboardStats)
	fakultas.Get("/participants", kencana.ListParticipants)
	fakultas.Get("/scores", kencana.ListScores)
	fakultas.Get("/scores/summary", kencana.ScoreSummary)
	fakultas.Get("/remedials", kencana.ListRemedials)
	fakultas.Get("/certificates", kencana.ListCertificates)
	fakultas.Get("/certificates/:id", kencana.GetCertificateDetail)
	fakultas.Post("/certificates/generate", kencana.GenerateCertificate)
	fakultas.Post("/certificates/generate-bulk", kencana.GenerateBulkCertificates)
	fakultas.Get("/banding", kencana.AdminListBanding)
	fakultas.Put("/banding/:id", kencana.AdminRespondBanding)
	fakultas.Get("/phase", kencana.GetFacultyPhase)
	fakultas.Put("/phase", kencana.UpdateFacultyPhase)
	fakultas.Post("/phase/start", kencana.StartFacultyPhase)
	fakultas.Post("/phase/complete", kencana.CompleteFacultyPhase)
	fakultas.Post("/phase/undo", kencana.UndoFacultyPhase)
	fakultas.Get("/stages", kencana.ListStages)
	fakultas.Post("/stages", kencana.CreateStage)
	fakultas.Put("/stages/:id", kencana.UpdateStage)
	fakultas.Get("/sessions", kencana.ListSessions)
	fakultas.Get("/sessions/:id", kencana.GetAdminSessionDetail)
	fakultas.Post("/sessions", kencana.CreateSession)
	fakultas.Put("/sessions/:id", kencana.UpdateSession)
	fakultas.Delete("/sessions/:id", kencana.DeleteSession)
	fakultas.Get("/sessions/:id/qr-token", kencana.GetSessionQRToken)
	fakultas.Post("/sessions/:id/qr-token/regenerate", kencana.RegenerateQRToken)
	fakultas.Get("/mentors", kencana.ListMentors)
	fakultas.Get("/students", kencana.SearchStudents)
	fakultas.Post("/mentors", kencana.CreateMentor)
	fakultas.Put("/mentors/:id", kencana.UpdateMentor)
	fakultas.Delete("/mentors/:id", kencana.DeleteMentor)
	fakultas.Get("/groups", kencana.ListGroups)
	fakultas.Post("/groups", kencana.CreateGroup)
	fakultas.Post("/groups/auto-assign", kencana.AutoAssignGroups)
	fakultas.Get("/groups/:id", kencana.GetGroup)
	fakultas.Put("/groups/:id", kencana.UpdateGroup)
	fakultas.Delete("/groups/:id", kencana.DeleteGroup)
	fakultas.Post("/groups/:id/members", kencana.AddGroupMembers)
	fakultas.Delete("/groups/:id/members/:studentId", kencana.RemoveGroupMember)
	// Announcements
	fakultas.Get("/announcements", kencana.ListAnnouncements)
	fakultas.Post("/announcements", kencana.CreateAnnouncement)
	fakultas.Delete("/announcements/:id", kencana.DeleteAnnouncement)

	mentor := api.Group("/kencana-mentor", middleware.KencanaMentorCheck)
	mentor.Get("/dashboard", kencana.MentorDashboard)
	mentor.Get("/profile", kencana.MentorProfile)
	mentor.Put("/profile", kencana.UpdateMentorProfile)
	mentor.Get("/available-students", kencana.MentorAvailableStudents)
	mentor.Get("/students", kencana.MentorStudents)
	mentor.Post("/invitations", kencana.MentorInviteStudents)
	mentor.Delete("/assignments/:id", kencana.MentorRemoveAssignment)
	mentor.Get("/students/:studentId/progress", kencana.MentorStudentProgress)
	mentor.Get("/students/:studentId/score", kencana.MentorStudentScore)
	mentor.Get("/students/:studentId/attendance", kencana.MentorStudentAttendance)
	mentor.Get("/students/:studentId/handbook", kencana.MentorStudentHandbook)
	mentor.Post("/students/:studentId/notes", kencana.MentorCreateNote)
	mentor.Post("/students/:studentId/score-items", kencana.MentorCreateScoreItem)
	mentor.Put("/students/:studentId/score-items", kencana.MentorUpsertBulkScoreItems)
	mentor.Post("/students/:studentId/handbook/review", kencana.MentorReviewHandbook)
	mentor.Get("/groups", kencana.MentorListGroups)
	mentor.Get("/groups/:id", kencana.MentorGetGroup)
	mentor.Get("/groups/:id/pdf", kencana.DownloadGroupPDF)
	mentor.Post("/groups/:id/members", kencana.MentorAddGroupMembers)
	mentor.Delete("/groups/:id/members/:studentId", kencana.MentorRemoveGroupMember)
	mentor.Get("/sessions", kencana.MentorListSessions)
	mentor.Get("/sessions/:sessionId/attendance", kencana.MentorGetSessionAttendance)
	mentor.Post("/sessions/:sessionId/attendance", kencana.MentorSubmitSessionAttendance)
	mentor.Get("/sessions/:sessionId/qr-token", kencana.MentorGetSessionQR)
}
