// ============================================================
// PERMISSION REGISTRY — Single Source of Truth
// Format: module.resource.action
// ============================================================

/**
 * All permissions used across the application.
 * Format: MODULE.RESOURCE.ACTION
 * 
 * Modules: core, akademik, kemahasiswaan, ormawa, kesehatan,
 *          psikologi, kencana, sistem, rbac
 * 
 * Actions: view, create, update, delete, manage, approve, export
 */
export const P = Object.freeze({
  // ─── CORE ──────────────────────────────────────────────
  DASHBOARD_VIEW:         'core.dashboard.view',
  PROFILE_VIEW:           'core.profile.view',
  PROFILE_UPDATE:         'core.profile.update',
  NOTIFICATIONS_VIEW:     'core.notifications.view',

  // ─── AKADEMIK ──────────────────────────────────────────
  FAKULTAS_VIEW:          'faculty.view',
  FAKULTAS_MANAGE:        'faculty.update',
  PRODI_VIEW:             'program_studi.view',
  PRODI_MANAGE:           'program_studi.update',
  PRODI_USERS_VIEW:       'prodi_users.view',
  PRODI_USERS_MANAGE:     'prodi_users.update',
  MAHASISWA_VIEW:         'students.view',
  MAHASISWA_CREATE:       'students.create',
  MAHASISWA_UPDATE:       'students.update',
  MAHASISWA_DELETE:       'students.delete',
  PMB_VIEW:               'system.pmb.view',
  PMB_SYNC:               'system.pmb.sync_sevima',
  DB_RESET:               'system.database.reset',
  DOSEN_VIEW:             'dosen.view',
  DOSEN_MANAGE:           'dosen.update',
  PERIODE_VIEW:           'akademik.view',
  PERIODE_MANAGE:         'akademik.update',

  // ─── KEMAHASISWAAN ─────────────────────────────────────
  BEASISWA_VIEW:          'scholarship.view',
  BEASISWA_MANAGE:        'scholarship.update',
  PRESTASI_VIEW:          'achievement.view',
  PRESTASI_MANAGE:        'achievement.update',
  ASPIRASI_VIEW:          'aspiration.view',
  ASPIRASI_RESPOND:       'aspiration.update',
  ASURANSI_VIEW:          'system.insurance.view',
  ASURANSI_MANAGE:        'system.insurance.manage',

  // ─── ORMAWA ────────────────────────────────────────────
  ORMAWA_VIEW:            'ormawa.organisasi.view',
  ORMAWA_MANAGE:          'ormawa.organisasi.manage',
  ORMAWA_KATEGORI_VIEW:   'ormawa.kategori.view',
  ORMAWA_KATEGORI_MANAGE: 'ormawa.kategori.manage',
  ORMAWA_DASHBOARD_VIEW:  'ormawa.dashboard.view',
  ORMAWA_MEMBERS_VIEW:    'ormawa.anggota.view',
  ORMAWA_MEMBERS_CREATE:  'ormawa.anggota.create',
  ORMAWA_MEMBERS_UPDATE:  'ormawa.anggota.update',
  ORMAWA_MEMBERS_DELETE:  'ormawa.anggota.delete',
  ORMAWA_STRUCTURE_VIEW:  'ormawa.struktur.view',
  ORMAWA_STRUCTURE_MANAGE:'ormawa.struktur.manage',
  ORMAWA_PROPOSAL_VIEW:   'ormawa.proposal.view',
  ORMAWA_PROPOSAL_CREATE: 'ormawa.proposal.create',
  ORMAWA_PROPOSAL_UPDATE: 'ormawa.proposal.update',
  ORMAWA_PROPOSAL_DELETE: 'ormawa.proposal.delete',
  ORMAWA_PROPOSAL_APPROVE:'ormawa.proposal.approve',
  ORMAWA_LPJ_VIEW:        'ormawa.lpj.view',
  ORMAWA_LPJ_CREATE:      'ormawa.lpj.create',
  ORMAWA_LPJ_UPDATE:      'ormawa.lpj.update',
  ORMAWA_LPJ_DELETE:      'ormawa.lpj.delete',
  ORMAWA_EVENT_VIEW:      'ormawa.event.view',
  ORMAWA_EVENT_CREATE:    'ormawa.event.create',
  ORMAWA_EVENT_UPDATE:    'ormawa.event.update',
  ORMAWA_EVENT_DELETE:    'ormawa.event.delete',
  ORMAWA_ATTENDANCE_VIEW: 'ormawa.absensi.view',
  ORMAWA_ATTENDANCE_MANAGE:'ormawa.absensi.manage',
  ORMAWA_FINANCE_VIEW:    'ormawa.keuangan.view',
  ORMAWA_FINANCE_CREATE:  'ormawa.keuangan.create',
  ORMAWA_FINANCE_DELETE:  'ormawa.keuangan.delete',
  ORMAWA_ASPIRATION_VIEW: 'ormawa.aspirasi.view',
  ORMAWA_ASPIRATION_RESPOND:'ormawa.aspirasi.respond',
  ORMAWA_ANNOUNCEMENT_VIEW:'ormawa.pengumuman.view',
  ORMAWA_ANNOUNCEMENT_CREATE:'ormawa.pengumuman.create',
  ORMAWA_ANNOUNCEMENT_UPDATE:'ormawa.pengumuman.update',
  ORMAWA_ANNOUNCEMENT_DELETE:'ormawa.pengumuman.delete',
  ORMAWA_RECRUITMENT_VIEW:'ormawa.rekrutmen.view',
  ORMAWA_RECRUITMENT_MANAGE:'ormawa.rekrutmen.manage',
  ORMAWA_RBAC_VIEW:       'ormawa.rbac.view',
  ORMAWA_RBAC_MANAGE:     'ormawa.rbac.manage',
  ORMAWA_SETTINGS_VIEW:   'ormawa.pengaturan.view',
  ORMAWA_SETTINGS_MANAGE: 'ormawa.pengaturan.manage',
  ORMAWA_GAMIFIKASI_VIEW: 'ormawa.gamifikasi.view',
  ORMAWA_GAMIFIKASI_MANAGE:'ormawa.gamifikasi.manage',
  ORMAWA_PAGU_VIEW:       'ormawa.pagu.view',
  ORMAWA_PAGU_MANAGE:     'ormawa.pagu.manage',

  // ─── PSIKOLOGI / KONSELING ─────────────────────────────
  PSIKOLOGI_DASHBOARD_VIEW:'psychologist.dashboard.view',
  PSIKOLOGI_VIEW:          'psychologist.view',
  PSIKOLOGI_MANAGE:        'psychologist.update',
  PSIKOLOGI_SCHEDULE_VIEW: 'psychologist.schedules.view',
  PSIKOLOGI_SCHEDULE_MANAGE:'psychologist.schedules.update',
  PSIKOLOGI_BOOKING_VIEW:  'psychologist.bookings.view',
  PSIKOLOGI_BOOKING_MANAGE:'psychologist.bookings.update',
  PSIKOLOGI_PATIENT_VIEW:  'psychologist.patients.view',
  PSIKOLOGI_PATIENT_MANAGE:'psychologist.patients.update',
  PSIKOLOGI_RECORD_VIEW:   'psychologist.medical_records.view',
  PSIKOLOGI_RECORD_MANAGE: 'psychologist.medical_records.update',
  PSIKOLOGI_REFERRAL_VIEW: 'psychologist.referrals.view',
  PSIKOLOGI_REFERRAL_MANAGE:'psychologist.referrals.update',
  PSIKOLOGI_REPORT_VIEW:   'psychologist.reports.view',
  PSIKOLOGI_ASSESSMENT_VIEW:'psychologist.assessment.view',
  PSIKOLOGI_ASSESSMENT_MANAGE:'psychologist.assessment.update',
  PSIKOLOGI_SETTINGS_VIEW: 'psychologist.settings.view',
  PSIKOLOGI_SETTINGS_MANAGE:'psychologist.settings.update',

  // ─── KESEHATAN / TENAGA KESEHATAN ──────────────────────
  KESEHATAN_DASHBOARD_VIEW:'health.dashboard.view',
  KESEHATAN_VIEW:          'health.view',
  KESEHATAN_MANAGE:        'health.update',
  KESEHATAN_SCHEDULE_VIEW: 'health.schedules.view',
  KESEHATAN_SCHEDULE_MANAGE:'health.schedules.update',
  KESEHATAN_BOOKING_VIEW:  'health.bookings.view',
  KESEHATAN_BOOKING_MANAGE:'health.bookings.update',
  KESEHATAN_PATIENT_VIEW:  'health.patients.view',
  KESEHATAN_RECORD_VIEW:   'health.medical_records.view',
  KESEHATAN_RECORD_MANAGE: 'health.medical_records.update',
  KESEHATAN_REFERRAL_VIEW: 'health.referrals.view',
  KESEHATAN_REFERRAL_MANAGE:'health.referrals.update',
  KESEHATAN_CLAIM_VIEW:    'health.claims.view',
  KESEHATAN_CLAIM_MANAGE:  'health.claims.update',
  KESEHATAN_BAP_VIEW:      'health.bap.view',
  KESEHATAN_BAP_MANAGE:    'health.bap.update',
  KESEHATAN_REPORT_VIEW:   'health.reports.view',
  KESEHATAN_SETTINGS_VIEW: 'health.settings.view',

  // ─── KENCANA / PKKMB ──────────────────────────────────
  KENCANA_DASHBOARD_VIEW:  'kencana.dashboard.view',
  KENCANA_PERIOD_VIEW:     'kencana.timeline.view',
  KENCANA_PERIOD_MANAGE:   'kencana.timeline.update',
  KENCANA_ANNOUNCEMENT_VIEW:'kencana.announcement.view',
  KENCANA_ANNOUNCEMENT_MANAGE:'kencana.announcement.update',
  KENCANA_PRE_VIEW:        'kencana.pre_kencana.view',
  KENCANA_PRE_MANAGE:      'kencana.pre_kencana.update',
  KENCANA_UNIV_VIEW:       'kencana.university.view',
  KENCANA_UNIV_MANAGE:     'kencana.university.update',
  KENCANA_FACULTY_VIEW:    'kencana.faculty_stages.view',
  KENCANA_FACULTY_MANAGE:  'kencana.faculty_stages.update',
  KENCANA_PARTICIPANT_VIEW:'kencana.participants.view',
  KENCANA_PARTICIPANT_MANAGE:'kencana.participants.update',
  KENCANA_SCORE_VIEW:      'kencana.scores.view',
  KENCANA_SCORE_MANAGE:    'kencana.scores.update',
  KENCANA_BANDING_VIEW:    'kencana.banding.view',
  KENCANA_BANDING_MANAGE:  'kencana.banding.update',
  KENCANA_SUMMARY_VIEW:    'kencana.score_summary.view',
  KENCANA_REMEDIAL_VIEW:   'kencana.remedials.view',
  KENCANA_REMEDIAL_MANAGE: 'kencana.remedials.update',
  KENCANA_CERTIFICATE_VIEW:'kencana.certificates.view',
  KENCANA_CERTIFICATE_MANAGE:'kencana.certificates.update',
  KENCANA_GROUP_VIEW:      'kencana.groups.view',
  KENCANA_GROUP_MANAGE:    'kencana.groups.update',
  KENCANA_MENTOR_VIEW:     'kencana.mentors.view',
  KENCANA_MENTOR_MANAGE:   'kencana.mentors.update',
  KENCANA_MENTOR_DASHBOARD:'kencana.mentor.dashboard',
  KENCANA_MENTOR_STUDENTS: 'kencana.mentor.view',
  KENCANA_MENTOR_SETTINGS: 'kencana.mentor.settings',
  KENCANA_SETTINGS_VIEW:   'kencana.settings.view',
  KENCANA_SETTINGS_MANAGE: 'kencana.settings.update',
  KENCANA_QUIZ_MANAGE:     'kencana.kuis.manage',

  // ─── STUDENT PORTAL ────────────────────────────────────
  STUDENT_DASHBOARD_VIEW:  'student.dashboard.view',
  STUDENT_PROFILE_VIEW:    'student.profil.view',
  STUDENT_PROFILE_UPDATE:  'student.profil.update',
  STUDENT_KENCANA_VIEW:    'student.kencana.view',
  STUDENT_COUNSELING_VIEW: 'student.konseling.view',
  STUDENT_HEALTH_VIEW:     'student.kesehatan.view',
  STUDENT_SCHOLARSHIP_VIEW:'student.beasiswa.view',
  STUDENT_ACHIEVEMENT_VIEW:'student.prestasi.view',
  STUDENT_ORGANISATION_VIEW:'student.organisasi.view',
  STUDENT_VOICE_VIEW:      'student.aspirasi.view',
  STUDENT_PRESENSI_VIEW:   'student.presensi.view',
  STUDENT_INSURANCE_VIEW:  'student.insurance.view',

  // ─── SISTEM / ADMIN ────────────────────────────────────
  RBAC_ROLES_VIEW:         'rbac.roles.view',
  RBAC_ROLES_MANAGE:       'rbac.roles.update',
  RBAC_USERS_VIEW:         'rbac.users.view',
  RBAC_USERS_MANAGE:       'rbac.users.update',
  AUDIT_VIEW:              'admin.audit.view',
  NEWS_VIEW:               'system.news.view',
  NEWS_MANAGE:             'system.news.manage',
  LANDING_VIEW:            'system.landing.view',
  LANDING_MANAGE:          'system.landing.manage',
  THEME_VIEW:              'system.theme.view',
  THEME_MANAGE:            'system.theme.manage',
  DOCUMENT_VIEW:           'system.document.view',
  DOCUMENT_MANAGE:         'system.document.manage',
  SETTINGS_VIEW:           'system_settings.view',
  SETTINGS_MANAGE:         'system_settings.update',
  DOCS_VIEW:               'system.docs.view',
  DOCS_MANAGE:             'system.docs.manage',
  INTEGRATION_SYNC:        'sistem.integrasi.sync',
  REPORT_VIEW:             'sistem.laporan.view',
  REPORT_EXPORT:           'sistem.laporan.export',
});


// ============================================================
// PERMISSION MIGRATION MAP — Old key → New key
// Used by permission bridge to translate legacy permissions
// ============================================================
export const PERMISSION_MIGRATION = Object.freeze({
  // Old ormawa permissions (legacy flat format)
  'view_dashboard':        P.CORE_DASHBOARD_VIEW,
  'view_notifications':    P.NOTIFICATIONS_VIEW,
  'view_members':          P.ORMAWA_MEMBERS_VIEW,
  'create_members':        P.ORMAWA_MEMBERS_CREATE,
  'edit_members':          P.ORMAWA_MEMBERS_UPDATE,
  'delete_members':        P.ORMAWA_MEMBERS_DELETE,
  'view_staff':            P.ORMAWA_MEMBERS_VIEW,
  'manage_staff':          P.ORMAWA_RECRUITMENT_MANAGE,
  'view_structure':        P.ORMAWA_STRUCTURE_VIEW,
  'manage_structure':      P.ORMAWA_STRUCTURE_MANAGE,
  'view_proposal':         P.ORMAWA_PROPOSAL_VIEW,
  'create_proposal':       P.ORMAWA_PROPOSAL_CREATE,
  'edit_proposal':         P.ORMAWA_PROPOSAL_UPDATE,
  'delete_proposal':       P.ORMAWA_PROPOSAL_DELETE,
  'view_lpj':              P.ORMAWA_LPJ_VIEW,
  'create_lpj':            P.ORMAWA_LPJ_CREATE,
  'edit_lpj':              P.ORMAWA_LPJ_UPDATE,
  'upload_lpj_doc':        P.ORMAWA_LPJ_UPDATE,
  'delete_lpj':            P.ORMAWA_LPJ_DELETE,
  'view_calendar':         P.ORMAWA_EVENT_VIEW,
  'create_calendar':       P.ORMAWA_EVENT_CREATE,
  'edit_calendar':         P.ORMAWA_EVENT_UPDATE,
  'delete_calendar':       P.ORMAWA_EVENT_DELETE,
  'view_attendance':       P.ORMAWA_ATTENDANCE_VIEW,
  'submit_attendance':     P.ORMAWA_ATTENDANCE_MANAGE,
  'edit_attendance':       P.ORMAWA_ATTENDANCE_MANAGE,
  'view_finance':          P.ORMAWA_FINANCE_VIEW,
  'create_finance':        P.ORMAWA_FINANCE_CREATE,
  'delete_finance':        P.ORMAWA_FINANCE_DELETE,
  'view_aspirations':      P.ORMAWA_ASPIRATION_VIEW,
  'respond_aspirations':   P.ORMAWA_ASPIRATION_RESPOND,
  'view_announcements':    P.ORMAWA_ANNOUNCEMENT_VIEW,
  'create_announcements':  P.ORMAWA_ANNOUNCEMENT_CREATE,
  'edit_announcements':    P.ORMAWA_ANNOUNCEMENT_UPDATE,
  'delete_announcements':  P.ORMAWA_ANNOUNCEMENT_DELETE,
  'view_settings':         P.ORMAWA_SETTINGS_VIEW,

  // Old ormawa dot-format
  'ormawa.core.view':          P.ORMAWA_DASHBOARD_VIEW,
  'ormawa.dashboard.view':     P.ORMAWA_DASHBOARD_VIEW,
  'ormawa.view':               P.ORMAWA_VIEW,
  'ormawa.manage':             P.ORMAWA_MANAGE,
  'ormawa.members.view':       P.ORMAWA_MEMBERS_VIEW,
  'ormawa.members.create':     P.ORMAWA_MEMBERS_CREATE,
  'ormawa.members.update':     P.ORMAWA_MEMBERS_UPDATE,
  'ormawa.members.delete':     P.ORMAWA_MEMBERS_DELETE,
  'ormawa.structure.view':     P.ORMAWA_STRUCTURE_VIEW,
  'ormawa.structure.manage':   P.ORMAWA_STRUCTURE_MANAGE,
  'ormawa.proposals.view':     P.ORMAWA_PROPOSAL_VIEW,
  'ormawa.proposals.create':   P.ORMAWA_PROPOSAL_CREATE,
  'ormawa.proposals.update':   P.ORMAWA_PROPOSAL_UPDATE,
  'ormawa.proposals.delete':   P.ORMAWA_PROPOSAL_DELETE,
  'ormawa.lpj.view':           P.ORMAWA_LPJ_VIEW,
  'ormawa.lpj.create':         P.ORMAWA_LPJ_CREATE,
  'ormawa.lpj.update':         P.ORMAWA_LPJ_UPDATE,
  'ormawa.lpj.delete':         P.ORMAWA_LPJ_DELETE,
  'ormawa.events.view':        P.ORMAWA_EVENT_VIEW,
  'ormawa.events.create':      P.ORMAWA_EVENT_CREATE,
  'ormawa.events.update':      P.ORMAWA_EVENT_UPDATE,
  'ormawa.events.delete':      P.ORMAWA_EVENT_DELETE,
  'ormawa.attendance.view':    P.ORMAWA_ATTENDANCE_VIEW,
  'ormawa.attendance.manage':  P.ORMAWA_ATTENDANCE_MANAGE,
  'ormawa.finance.view':       P.ORMAWA_FINANCE_VIEW,
  'ormawa.finance.create':     P.ORMAWA_FINANCE_CREATE,
  'ormawa.finance.delete':     P.ORMAWA_FINANCE_DELETE,
  'ormawa.aspirations.view':   P.ORMAWA_ASPIRATION_VIEW,
  'ormawa.aspirations.update': P.ORMAWA_ASPIRATION_RESPOND,
  'ormawa.announcements.view': P.ORMAWA_ANNOUNCEMENT_VIEW,
  'ormawa.announcements.create': P.ORMAWA_ANNOUNCEMENT_CREATE,
  'ormawa.announcements.update': P.ORMAWA_ANNOUNCEMENT_UPDATE,
  'ormawa.announcements.delete': P.ORMAWA_ANNOUNCEMENT_DELETE,
  'ormawa.notifications.view':   P.NOTIFICATIONS_VIEW,
  'ormawa.notifications.manage': P.NOTIFICATIONS_VIEW,
  'ormawa.rbac.view':          P.ORMAWA_RBAC_VIEW,
  'ormawa.settings.view':      P.ORMAWA_SETTINGS_VIEW,
  'ormawa.recruitment.view':   P.ORMAWA_RECRUITMENT_VIEW,

  // Old faculty underscore format
  'faculty.dashboard.view':    P.DASHBOARD_VIEW,
  'faculty.view':              P.FAKULTAS_VIEW,
  'faculty.create':            P.FAKULTAS_MANAGE,
  'faculty.update':            P.FAKULTAS_MANAGE,
  'faculty.delete':            P.FAKULTAS_MANAGE,
  'faculty.manage':            P.FAKULTAS_MANAGE,
  'faculty_rbac.view':         P.RBAC_ROLES_VIEW,
  'faculty_rbac.manage':       P.RBAC_ROLES_MANAGE,
  'faculty_report.view':       P.REPORT_VIEW,
  'faculty_settings.view':     P.SETTINGS_VIEW,
  'faculty_profile.view':      P.PROFILE_VIEW,
  'faculty_health.view':       P.KESEHATAN_DASHBOARD_VIEW,
  'faculty_ormawa.view':       P.ORMAWA_VIEW,
  'faculty_proposal.view':     P.ORMAWA_PROPOSAL_APPROVE,
  'faculty.aspiration.view':   P.ASPIRASI_VIEW,
  'faculty.achievement.view':  P.PRESTASI_VIEW,
  'faculty.scholarship.view':  P.BEASISWA_VIEW,
  'faculty.counseling.view':   P.PSIKOLOGI_VIEW,

  // Old admin format
  'admin.dashboard.view':      P.DASHBOARD_VIEW,
  'admin.audit.view':          P.AUDIT_VIEW,

  // Old health format
  'health.view':               P.KESEHATAN_VIEW,
  'health.dashboard.view':     P.KESEHATAN_DASHBOARD_VIEW,
  'health.schedules.view':     P.KESEHATAN_SCHEDULE_VIEW,
  'health.schedules.manage':   P.KESEHATAN_SCHEDULE_MANAGE,
  'health.bookings.view':      P.KESEHATAN_BOOKING_VIEW,
  'health.bookings.manage':    P.KESEHATAN_BOOKING_MANAGE,
  'health.patients.view':      P.KESEHATAN_PATIENT_VIEW,
  'health.medical_records.view': P.KESEHATAN_RECORD_VIEW,
  'health.medical_records.manage': P.KESEHATAN_RECORD_MANAGE,
  'health.referrals.view':     P.KESEHATAN_REFERRAL_VIEW,
  'health.referrals.update':   P.KESEHATAN_REFERRAL_MANAGE,
  'health.bap.view':           P.KESEHATAN_BAP_VIEW,
  'health.bap.manage':         P.KESEHATAN_BAP_MANAGE,
  'health.reports.view':       P.KESEHATAN_REPORT_VIEW,
  'health_claims.view':        P.KESEHATAN_CLAIM_VIEW,

  // Old psychologist format
  'psychologist.view':                P.PSIKOLOGI_VIEW,
  'psychologist.core':                P.PSIKOLOGI_MANAGE,
  'psychologist.dashboard.view':      P.PSIKOLOGI_DASHBOARD_VIEW,
  'psychologist.schedules.view':      P.PSIKOLOGI_SCHEDULE_VIEW,
  'psychologist.schedules.create':    P.PSIKOLOGI_SCHEDULE_MANAGE,
  'psychologist.schedules.update':    P.PSIKOLOGI_SCHEDULE_MANAGE,
  'psychologist.schedules.delete':    P.PSIKOLOGI_SCHEDULE_MANAGE,
  'psychologist.bookings.view':       P.PSIKOLOGI_BOOKING_VIEW,
  'psychologist.bookings.create':     P.PSIKOLOGI_BOOKING_MANAGE,
  'psychologist.bookings.update':     P.PSIKOLOGI_BOOKING_MANAGE,
  'psychologist.bookings.delete':     P.PSIKOLOGI_BOOKING_MANAGE,
  'psychologist.patients.view':       P.PSIKOLOGI_PATIENT_VIEW,
  'psychologist.patients.create':     P.PSIKOLOGI_PATIENT_MANAGE,
  'psychologist.patients.update':     P.PSIKOLOGI_PATIENT_MANAGE,
  'psychologist.patients.delete':     P.PSIKOLOGI_PATIENT_MANAGE,
  'psychologist.medical_records.view':   P.PSIKOLOGI_RECORD_VIEW,
  'psychologist.medical_records.create': P.PSIKOLOGI_RECORD_MANAGE,
  'psychologist.medical_records.update': P.PSIKOLOGI_RECORD_MANAGE,
  'psychologist.medical_records.delete': P.PSIKOLOGI_RECORD_MANAGE,
  'psychologist.referrals.view':      P.PSIKOLOGI_REFERRAL_VIEW,
  'psychologist.referrals.create':    P.PSIKOLOGI_REFERRAL_MANAGE,
  'psychologist.referrals.update':    P.PSIKOLOGI_REFERRAL_MANAGE,
  'psychologist.referrals.delete':    P.PSIKOLOGI_REFERRAL_MANAGE,
  'psychologist.reports.view':        P.PSIKOLOGI_REPORT_VIEW,
  'psychologist.reports.create':      P.PSIKOLOGI_REPORT_VIEW,
  'psychologist.notifications.view':  P.NOTIFICATIONS_VIEW,
  'psychologist.settings.view':       P.PSIKOLOGI_SETTINGS_VIEW,
  'psychologist.settings.update':     P.PSIKOLOGI_SETTINGS_MANAGE,
  'view_psychologist_medical_records':P.PSIKOLOGI_RECORD_VIEW,

  // Old akademik format
  'students.view':             P.MAHASISWA_VIEW,
  'students.create':           P.MAHASISWA_CREATE,
  'students.update':           P.MAHASISWA_UPDATE,
  'students.delete':           P.MAHASISWA_DELETE,
  'dosen.view':                P.DOSEN_VIEW,
  'dosen.manage':              P.DOSEN_MANAGE,
  'program_studi.view':        P.PRODI_VIEW,
  'program_studi.manage':      P.PRODI_MANAGE,
  'prodi_users.view':          P.PRODI_USERS_VIEW,
  'akademik.view':             P.PERIODE_VIEW,
  'akademik.manage':           P.PERIODE_MANAGE,
  'academic_periods.view':     P.PERIODE_VIEW,

  // Old kemahasiswaan format
  'scholarship.view':          P.BEASISWA_VIEW,
  'scholarship.manage':        P.BEASISWA_MANAGE,
  'achievement.view':          P.PRESTASI_VIEW,
  'achievement.manage':        P.PRESTASI_MANAGE,
  'achievement.create':        P.PRESTASI_MANAGE,
  'achievement.update':        P.PRESTASI_MANAGE,
  'aspiration.view':           P.ASPIRASI_VIEW,
  'aspiration.respond':        P.ASPIRASI_RESPOND,

  // Old kencana format (most already use module.resource.action)
  'kencana.dashboard.view':    P.KENCANA_DASHBOARD_VIEW,
  'kencana.timeline.view':     P.KENCANA_PERIOD_VIEW,
  'kencana.timeline.create':   P.KENCANA_PERIOD_MANAGE,
  'kencana.timeline.update':   P.KENCANA_PERIOD_MANAGE,
  'kencana.timeline.delete':   P.KENCANA_PERIOD_MANAGE,
  'kencana.announcement.view': P.KENCANA_ANNOUNCEMENT_VIEW,
  'kencana.pre_kencana.view':  P.KENCANA_PRE_VIEW,
  'kencana.pre_kencana.create':P.KENCANA_PRE_MANAGE,
  'kencana.pre_kencana.update':P.KENCANA_PRE_MANAGE,
  'kencana.pre_kencana.delete':P.KENCANA_PRE_MANAGE,
  'kencana.university.view':   P.KENCANA_UNIV_VIEW,
  'kencana.university.create': P.KENCANA_UNIV_MANAGE,
  'kencana.university.update': P.KENCANA_UNIV_MANAGE,
  'kencana.university.delete': P.KENCANA_UNIV_MANAGE,
  'kencana.faculty_stages.view':  P.KENCANA_FACULTY_VIEW,
  'kencana.faculty_stages.create':P.KENCANA_FACULTY_MANAGE,
  'kencana.faculty_stages.update':P.KENCANA_FACULTY_MANAGE,
  'kencana.faculty_stages.delete':P.KENCANA_FACULTY_MANAGE,
  'kencana.participants.view': P.KENCANA_PARTICIPANT_VIEW,
  'kencana.participants.create':P.KENCANA_PARTICIPANT_MANAGE,
  'kencana.participants.update':P.KENCANA_PARTICIPANT_MANAGE,
  'kencana.participants.delete':P.KENCANA_PARTICIPANT_MANAGE,
  'kencana.scores.view':       P.KENCANA_SCORE_VIEW,
  'kencana.scores.create':     P.KENCANA_SCORE_MANAGE,
  'kencana.scores.update':     P.KENCANA_SCORE_MANAGE,
  'kencana.scores.delete':     P.KENCANA_SCORE_MANAGE,
  'kencana.banding.view':      P.KENCANA_BANDING_VIEW,
  'kencana.banding.update':    P.KENCANA_BANDING_MANAGE,
  'kencana.score_summary.view':P.KENCANA_SUMMARY_VIEW,
  'kencana.remedials.view':    P.KENCANA_REMEDIAL_VIEW,
  'kencana.remedials.create':  P.KENCANA_REMEDIAL_MANAGE,
  'kencana.remedials.update':  P.KENCANA_REMEDIAL_MANAGE,
  'kencana.remedials.delete':  P.KENCANA_REMEDIAL_MANAGE,
  'kencana.certificates.view': P.KENCANA_CERTIFICATE_VIEW,
  'kencana.certificates.create':P.KENCANA_CERTIFICATE_MANAGE,
  'kencana.certificates.update':P.KENCANA_CERTIFICATE_MANAGE,
  'kencana.certificates.delete':P.KENCANA_CERTIFICATE_MANAGE,
  'kencana.groups.view':       P.KENCANA_GROUP_VIEW,
  'kencana.groups.create':     P.KENCANA_GROUP_MANAGE,
  'kencana.groups.update':     P.KENCANA_GROUP_MANAGE,
  'kencana.groups.delete':     P.KENCANA_GROUP_MANAGE,
  'kencana.mentors.view':      P.KENCANA_MENTOR_VIEW,
  'kencana.mentors.create':    P.KENCANA_MENTOR_MANAGE,
  'kencana.mentors.update':    P.KENCANA_MENTOR_MANAGE,
  'kencana.mentors.delete':    P.KENCANA_MENTOR_MANAGE,
  'kencana.notifications.view':P.NOTIFICATIONS_VIEW,
  'kencana.settings.view':     P.KENCANA_SETTINGS_VIEW,
  'kencana.settings.update':   P.KENCANA_SETTINGS_MANAGE,
  'kencana.mentor.dashboard':  P.KENCANA_MENTOR_DASHBOARD,
  'kencana.mentor.view':       P.KENCANA_MENTOR_STUDENTS,
  'kencana.mentor.update':     P.KENCANA_MENTOR_MANAGE,
  'kencana.mentor.settings':   P.KENCANA_MENTOR_SETTINGS,
  'kencana.faculty.dashboard': P.KENCANA_FACULTY_VIEW,
  'kencana.attendance.view':   P.KENCANA_PARTICIPANT_VIEW,

  // Old student format
  'student.dashboard.view':    P.STUDENT_DASHBOARD_VIEW,
  'student.profile.view':      P.STUDENT_PROFILE_VIEW,
  'student.profile.update':    P.STUDENT_PROFILE_UPDATE,
  'student.kencana.view':      P.STUDENT_KENCANA_VIEW,
  'student_kencana_view':      P.STUDENT_KENCANA_VIEW,
  'student.counseling.view':   P.STUDENT_COUNSELING_VIEW,
  'student.health.view':       P.STUDENT_HEALTH_VIEW,
  'student.scholarship.view':  P.STUDENT_SCHOLARSHIP_VIEW,
  'student.achievement.view':  P.STUDENT_ACHIEVEMENT_VIEW,
  'student.organisasi.view':   P.STUDENT_ORGANISATION_VIEW,
  'student.voice.view':        P.STUDENT_VOICE_VIEW,

  // Old system format
  'admin.full_access':         '*',
  'admin.profile.view':        P.PROFILE_VIEW,
  'admin.profile.update':      P.PROFILE_UPDATE,
  'rbac.roles.view':           P.RBAC_ROLES_VIEW,
  'rbac.roles.manage':         P.RBAC_ROLES_MANAGE,
  'rbac.roles.create':         P.RBAC_ROLES_MANAGE,
  'rbac.roles.update':         P.RBAC_ROLES_MANAGE,
  'rbac.roles.delete':         P.RBAC_ROLES_MANAGE,
  'rbac.users.view':           P.RBAC_USERS_VIEW,
  'rbac.users.create':         P.RBAC_USERS_MANAGE,
  'rbac.users.update':         P.RBAC_USERS_MANAGE,
  'rbac.users.delete':         P.RBAC_USERS_MANAGE,
  'rbac.permissions.assign':   P.RBAC_USERS_MANAGE,
  'user.manage':               P.RBAC_USERS_MANAGE,
  'news.view':                 P.NEWS_VIEW,
  'news.manage':               P.NEWS_MANAGE,
  'system.news.view':          P.NEWS_VIEW,
  'system.landing.view':       P.LANDING_VIEW,
  'system.theme.view':         P.THEME_VIEW,
  'system.document.view':      P.DOCUMENT_VIEW,
  'system.docs.view':          P.DOCS_VIEW,
  'system.category.view':      P.ORMAWA_KATEGORI_VIEW,
  'system.finance.view':       P.ORMAWA_PAGU_VIEW,
  'system.insurance.view':     P.ASURANSI_VIEW,
  'system_settings.view':      P.SETTINGS_VIEW,
  'landing.manage':            P.LANDING_MANAGE,
  'theme.manage':              P.THEME_MANAGE,
  'document.manage':           P.DOCUMENT_MANAGE,
  'docs.manage':               P.DOCS_MANAGE,
  'integration.sync':          P.INTEGRATION_SYNC,
  'academic_settings.view':    P.SETTINGS_VIEW,
  'academic_settings.manage':  P.SETTINGS_MANAGE,
  'proposal.univ.view':        P.ORMAWA_PROPOSAL_APPROVE,
  'proposal.univ.approve':     P.ORMAWA_PROPOSAL_APPROVE,
  'counseling.view':           P.PSIKOLOGI_VIEW,
  'counseling.manage':         P.PSIKOLOGI_MANAGE,
  'report.view':               P.REPORT_VIEW,
});


/**
 * Translate a permission key from any format to the new standard format.
 * Returns the original key if no mapping exists (it might already be new format).
 */
export function migratePermission(key) {
  return PERMISSION_MIGRATION[key] || key;
}

/**
 * Translate an array of permissions from old format to new.
 * Deduplicates results.
 */
export function migratePermissions(keys) {
  const migrated = new Set();
  for (const key of keys) {
    migrated.add(migratePermission(key));
  }
  return [...migrated];
}
